//! Minimal hand-written FFI over libz3's stable C API, plus fork-based
//! isolation for each query.
//!
//! Deliberately NOT `z3-sys`/`z3` crates: those regenerate bindings with
//! bindgen at build time (libclang dependency) for hundreds of entry
//! points, of which this backend needs eight, all of which have been ABI-
//! stable for a decade. Linking is plain `-lz3`; building requires
//! `libz3-dev` (only the shared library is needed).
//!
//! # Why fork
//!
//! z3's soft timeout and even an explicit `Z3_interrupt` from another
//! thread are advisory - measured on 4.8.12, the E-matching loop that the
//! exp-axiom mode provokes never polls cancellation (a 3-second soft
//! timeout still hadn't fired 90 seconds in). The only reliable bound is
//! a hard kill, and in-process there is nothing safe to kill. Each query
//! therefore evaluates in a forked child: the child inherits the query
//! string and the linked libz3 by copy-on-write (no binary to exec, no
//! query serialization), writes the solver's small textual output to a
//! pipe, and `_exit`s; the parent reads with a deadline and SIGKILLs on
//! expiry. This also restores per-element crash containment - a z3
//! internal abort takes down one child, not the run.
//!
//! Fork safety: the process must effectively be single-threaded when a
//! query runs (a child forked from a multithreaded process may inherit a
//! held malloc lock and deadlock - which the deadline then converts into
//! a spurious timeout). The volta binaries are single-threaded; callers
//! embedding this crate from worker threads should serialize their calls.

use std::ffi::{CStr, CString, c_char, c_int, c_uint, c_void};
use std::time::{Duration, Instant};

type Z3Config = *mut c_void;
type Z3Context = *mut c_void;

#[link(name = "z3")]
unsafe extern "C" {
    fn Z3_mk_config() -> Z3Config;
    fn Z3_del_config(cfg: Z3Config);
    fn Z3_mk_context(cfg: Z3Config) -> Z3Context;
    fn Z3_del_context(ctx: Z3Context);
    fn Z3_set_error_handler(
        ctx: Z3Context,
        handler: Option<unsafe extern "C" fn(Z3Context, c_int)>,
    );
    fn Z3_eval_smtlib2_string(ctx: Z3Context, s: *const c_char) -> *const c_char;
    fn Z3_global_param_set(param_id: *const c_char, param_value: *const c_char);
    fn Z3_get_version(major: *mut c_uint, minor: *mut c_uint, build: *mut c_uint, rev: *mut c_uint);
}

/// z3's default error handler aborts the process; errors must instead
/// surface as `(error ...)` lines in the eval output.
unsafe extern "C" fn ignore_errors(_ctx: Z3Context, _code: c_int) {}

/// The linked z3 library version, e.g. "4.8.12".
pub fn z3_version() -> String {
    let (mut major, mut minor, mut build, mut rev) = (0, 0, 0, 0);
    unsafe { Z3_get_version(&mut major, &mut minor, &mut build, &mut rev) };
    format!("{}.{}.{}", major, minor, build)
}

/// One query's fate, as observed by the parent.
pub enum EvalOutcome {
    /// The child finished and this is the solver's textual output.
    Output(String),
    /// The deadline expired and the child was killed - the definitive
    /// timeout signal (z3's own soft timeout is unreliable, see module
    /// docs).
    HardTimeout,
    /// The child died without producing output (z3 crash/abort); the
    /// payload describes how.
    ChildDied(String),
}

/// In-process evaluation - runs inside the forked child. Kept as its own
/// function so the child does the minimum: eval, hand the bytes back.
fn eval_in_process(c_query: &CStr) -> String {
    unsafe {
        let cfg = Z3_mk_config();
        let ctx = Z3_mk_context(cfg);
        Z3_set_error_handler(ctx, Some(ignore_errors));
        let out = Z3_eval_smtlib2_string(ctx, c_query.as_ptr());
        let result = if out.is_null() {
            String::new()
        } else {
            CStr::from_ptr(out).to_string_lossy().into_owned()
        };
        Z3_del_context(ctx);
        Z3_del_config(cfg);
        result
    }
}

/// Evaluate one self-contained SMT-LIB2 script in a forked child,
/// enforcing `timeout` (`None` = no limit) with SIGKILL. z3's soft
/// timeout is also set (belt and suspenders: when it does fire, the
/// output carries a `canceled` reason a little before the hard deadline).
pub fn eval_smtlib2(query: &str, timeout: Option<Duration>) -> EvalOutcome {
    // The query text is generated by `translate` and never contains NUL.
    let c_query = CString::new(query).expect("SMT query contained a NUL byte");
    let timeout_ms = match timeout {
        // Millisecond granularity, minimum 1ms; u32::MAX is z3's default
        // "effectively unlimited" value.
        Some(t) => (t.as_millis().min(u64::from(u32::MAX - 1) as u128) as u32).max(1),
        None => u32::MAX,
    };
    // Set in the parent: the global parameter table is inherited by the
    // child along with everything else.
    let param = CString::new("timeout").unwrap();
    let value = CString::new(timeout_ms.to_string()).unwrap();
    unsafe { Z3_global_param_set(param.as_ptr(), value.as_ptr()) };

    let mut fds = [0 as c_int; 2];
    if unsafe { libc::pipe(fds.as_mut_ptr()) } != 0 {
        return EvalOutcome::ChildDied("pipe() failed".to_string());
    }
    let (read_fd, write_fd) = (fds[0], fds[1]);

    let pid = unsafe { libc::fork() };
    if pid < 0 {
        unsafe {
            libc::close(read_fd);
            libc::close(write_fd);
        }
        return EvalOutcome::ChildDied("fork() failed".to_string());
    }

    if pid == 0 {
        // Child: evaluate and stream the (small) output back. Nothing
        // here returns; on any failure the exit status tells the parent.
        unsafe { libc::close(read_fd) };
        let out = eval_in_process(&c_query);
        let bytes = out.as_bytes();
        let mut written = 0;
        while written < bytes.len() {
            let n = unsafe {
                libc::write(
                    write_fd,
                    bytes[written..].as_ptr() as *const c_void,
                    bytes.len() - written,
                )
            };
            if n <= 0 {
                break;
            }
            written += n as usize;
        }
        unsafe { libc::_exit(0) };
    }

    // Parent.
    unsafe { libc::close(write_fd) };
    let deadline = timeout.map(|t| {
        // Grace on top of z3's soft timeout so a clean in-band `canceled`
        // result wins when the solver does honor cancellation.
        Instant::now() + t + Duration::from_millis(500).max(t / 10)
    });
    let mut out = Vec::new();
    let mut buf = [0u8; 4096];
    let outcome = loop {
        let remaining_ms: c_int = match deadline {
            None => -1,
            Some(d) => {
                let now = Instant::now();
                if now >= d {
                    break None;
                }
                (d - now).as_millis().min(60_000) as c_int
            }
        };
        let mut pfd = libc::pollfd {
            fd: read_fd,
            events: libc::POLLIN,
            revents: 0,
        };
        let pr = unsafe { libc::poll(&mut pfd, 1, remaining_ms) };
        if pr < 0 {
            if std::io::Error::last_os_error().kind() == std::io::ErrorKind::Interrupted {
                continue;
            }
            break Some(EvalOutcome::ChildDied("poll() failed".to_string()));
        }
        if pr == 0 {
            continue; // re-check deadline
        }
        let n = unsafe { libc::read(read_fd, buf.as_mut_ptr() as *mut c_void, buf.len()) };
        if n < 0 {
            if std::io::Error::last_os_error().kind() == std::io::ErrorKind::Interrupted {
                continue;
            }
            break Some(EvalOutcome::ChildDied("read() failed".to_string()));
        }
        if n == 0 {
            // EOF: child closed the pipe (finished or died).
            break Some(EvalOutcome::Output(
                String::from_utf8_lossy(&out).into_owned(),
            ));
        }
        out.extend_from_slice(&buf[..n as usize]);
    };
    unsafe { libc::close(read_fd) };

    match outcome {
        None => {
            // Deadline expired: hard-kill and reap.
            unsafe {
                libc::kill(pid, libc::SIGKILL);
                let mut status: c_int = 0;
                libc::waitpid(pid, &mut status, 0);
            }
            EvalOutcome::HardTimeout
        }
        Some(EvalOutcome::Output(text)) => {
            let mut status: c_int = 0;
            unsafe { libc::waitpid(pid, &mut status, 0) };
            let exited_cleanly = libc::WIFEXITED(status) && libc::WEXITSTATUS(status) == 0;
            if exited_cleanly {
                EvalOutcome::Output(text)
            } else if libc::WIFSIGNALED(status) {
                EvalOutcome::ChildDied(format!(
                    "z3 worker killed by signal {}",
                    libc::WTERMSIG(status)
                ))
            } else {
                EvalOutcome::ChildDied(format!(
                    "z3 worker exited with status {}",
                    libc::WEXITSTATUS(status)
                ))
            }
        }
        Some(other) => {
            unsafe {
                libc::kill(pid, libc::SIGKILL);
                let mut status: c_int = 0;
                libc::waitpid(pid, &mut status, 0);
            }
            other
        }
    }
}
